# Generated by Django 6.1.1 on 2026-09-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['created_at']},
        ),
    ]
